/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// LAST MODIFIED: 10/20/2014 by Justin
// TODO: Add DB Support

package restaurant.wiz;

import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author reza7634
 */
public class Employeemode extends javax.swing.JFrame {

	/**
	 * Creates new form Employeemode
	 */
	public Employeemode() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		entree = new javax.swing.JList();

		// user can only select one
		entree.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		desert = new javax.swing.JList();
		desert.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jLabel4 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		misc = new javax.swing.JList();
		misc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		nonalc = new javax.swing.JList();
		nonalc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jLabel6 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		alc = new javax.swing.JList();
		alc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		finalizeorder = new javax.swing.JButton();
		clear = new javax.swing.JButton();
		exit = new javax.swing.JButton();
		update = new javax.swing.JButton();
		managermode = new javax.swing.JButton();
		orderedItems = new javax.swing.JScrollPane();
		listModel = new DefaultListModel();
		order = new JList(listModel);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Menu:");

		jLabel2.setText("Entree:");

		entree.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Steak and cheese", "double ham",
					"meatlovers dream", "fishy fishy" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(entree);

		entree.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent arg0) {

				listModel.addElement(entree.getSelectedValue());
				order.ensureIndexIsVisible(listModel.size() - 1);

			}

		});

		jLabel3.setText("Desert:");

		desert.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(desert);

		desert.addMouseListener(new MouseAdapter() {

			// user added a menu item
			@Override
			public void mouseClicked(MouseEvent arg0) {

				listModel.addElement(desert.getSelectedValue());
				order.ensureIndexIsVisible(listModel.size() - 1);

			}

		});

		jLabel4.setText("Misc.:");

		misc.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "jay", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(misc);

		misc.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent arg0) {

				listModel.addElement(misc.getSelectedValue());
				order.ensureIndexIsVisible(listModel.size() - 1);

			}

		});

		jLabel5.setText("Nonalcohol:");

		nonalc.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "reza", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane4.setViewportView(nonalc);

		nonalc.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent arg0) {

				listModel.addElement(nonalc.getSelectedValue());
				order.ensureIndexIsVisible(listModel.size() - 1);

			}

		});

		jLabel6.setText("Alcohol:");

		alc.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane5.setViewportView(alc);

		alc.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent arg0) {

				listModel.addElement(alc.getSelectedValue());
				order.ensureIndexIsVisible(listModel.size() - 1);

			}

		});
		
		// cumulative order list
		orderedItems.setViewportView(order);
		
		// remove items from order list one-by-one
		order.addMouseListener(new MouseAdapter() {
			
			@Override
			public void mouseClicked(MouseEvent arg0) {
				listModel.removeElement(order.getSelectedValue());
			}
		});
		

		finalizeorder.setText("Finalize order");
		finalizeorder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				finalizeorderActionPerformed(evt);
			}
		});

		clear.setText("Clear");
		clear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearActionPerformed(evt);
			}
		});

		exit.setText("Exit");
		exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitActionPerformed(evt);
			}
		});

		update.setText("Update"); // what is this

		managermode.setText("Manager Mode");
		
		/*
		RestaurantWiz wiz = new RestaurantWiz();
		
		if ("admin".equals(wiz.manager.getText()) && "admin123".equals(wiz.managerpass.getText())) {
			managermode.setEnabled(true);
		} else {
			managermode.setEnabled(false);
		}
		*/
		
		
		managermode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				managermodeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						41,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jScrollPane1)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addGap(28, 28,
																		28)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane2)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						69,
																						Short.MAX_VALUE)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		finalizeorder)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		26,
																		Short.MAX_VALUE)
																.addComponent(
																		clear,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		64,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jLabel4,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jScrollPane3,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														64, Short.MAX_VALUE)
												.addComponent(
														exit,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane4)
																				.addComponent(
																						jLabel5,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						61,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						59,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jScrollPane5)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		update)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		managermode)))
								.addGap(29, 29, 29)
								.addComponent(orderedItems,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										244,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(19, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										23,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(jLabel6))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(orderedItems)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		jScrollPane1)
																.addComponent(
																		jScrollPane4,
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(
																		jScrollPane5,
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(
																		jScrollPane2)
																.addComponent(
																		jScrollPane3,
																		javax.swing.GroupLayout.Alignment.TRAILING)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(finalizeorder)
												.addComponent(clear)
												.addComponent(exit)
												.addComponent(update)
												.addComponent(managermode))
								.addContainerGap(19, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void close() {

		WindowEvent winClosingEvent = new WindowEvent(this,
				WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue()
				.postEvent(winClosingEvent);

	}

	private void finalizeorderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_finalizeorderActionPerformed

		close();
		Payment s = new Payment();
		s.setVisible(true);

	}// GEN-LAST:event_finalizeorderActionPerformed

	private void clearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearActionPerformed

		// clear selections and ordered item list
		if (evt.getSource() == clear) {
			listModel.clear();
			misc.clearSelection();
			alc.clearSelection();
			desert.clearSelection();
			entree.clearSelection();
			nonalc.clearSelection();
		}

	}// GEN-LAST:event_clearActionPerformed

	private void exitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitActionPerformed

	private void managermodeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_managermodeActionPerformed

		close();
		Managermode s = new Managermode();
		s.setVisible(true);

	}// GEN-LAST:event_managermodeActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Employeemode.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Employeemode.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Employeemode.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Employeemode.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Employeemode().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JList alc;
	private javax.swing.JButton clear;
	private javax.swing.JList desert;
	private javax.swing.JList entree;
	private javax.swing.JButton exit;
	private javax.swing.JButton finalizeorder;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane orderedItems;
	private javax.swing.JButton managermode;
	private javax.swing.JList misc;
	private javax.swing.JList nonalc;
	private javax.swing.JButton update;
	private javax.swing.JList order;
	private javax.swing.DefaultListModel listModel;
	// End of variables declaration//GEN-END:variables
}
